config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "home#index"
  resources :items
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  get "/search", to: "items#search"

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/item.rb
class Item < ApplicationRecord
  has_one_attached :fileobj
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    render
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: %i[ show edit update destroy ]

  # GET /items or /items.json
  def index
    @items = Item.all
  end

  # GET /items/1 or /items/1.json
  def show
    @filedata = @item.fileobj.image?
    @preview = @item.fileobj
    if(@item.fileobj.previewable?)
      @item.fileobj.preview(resize_to_limit: [100, 100]).processed.url
      @preview = @item.fileobj.preview(resize_to_limit: [100, 100]).image
    end
    #if(@item.fileobj.video?)
    #  @video = 
  end

  # GET /items/new
  def new
    @item = Item.new
  end

  # GET /items/1/edit
  def edit
  end

  # POST /items or /items.json
  def create
    @item = Item.new(item_params)
    #@item.fileobj.attach(params[:fileobj])

    @item.filename = @item.fileobj.filename

    if(@item.fileobj.audio?)
      @item.filetype = "audio"
    elsif(@item.fileobj.image?)
      @item.filetype = "image"
      #@item.dimensions = @item.fileobj.metadata["width"] + " x " + @item.fileobj.metadata["height"]
    elsif(@item.fileobj.video?)
      @item.filetype = "video"
      #@item.dimensions = @item.fileobj.metadata["width"] + " x " + @item.fileobj.metadata["height"]
    elsif(@item.fileobj.text?)
      @item.filetype = "document"
    end
 
    #if(@item.fileobj.analyzed?)
      
    #end

    respond_to do |format|
      if @item.save
        #format.html { redirect_to item_url(@item), notice: "Item was successfully created." }
        format.html { redirect_to edit_item_path(@item), notice: "Item was successfully created." }
        format.json { render :show, status: :created, location: @item }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /items/1 or /items/1.json
  def update
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to item_url(@item), notice: "Item was successfully updated." }
        format.json { render :show, status: :ok, location: @item }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1 or /items/1.json
  def destroy
    @item.destroy!

    respond_to do |format|
      format.html { redirect_to items_url, notice: "Item was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def search
    @results = Item.where("filename LIKE ?", "%" + Item.sanitize_sql_like(params[:filename]) + "%")
    #Rails.logger.debug @results
    qtyword = "items"
    if(@results.length == 1)
      qtyword = "item"
    end
    @summary = @results.length.to_s + " #{qtyword} found for '#{params[:filename]}'"
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def item_params
      params.require(:item).permit(:filename, :filetype, :fileformat, :filesize, :dimensions, :content_description, :content_keywords, :file_date_created, :fileobj)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/home/index.html.erb
<h1>DAMit Homepage</h1>

<h2>Add a New Item</h2>
<div>
  <a href="/items/new" class="btn btn-outline-primary">Upload File</a>

</div>
<div>
  <button class="btn btn-outline-secondary">Manually Enter Asset Data</button>
</div>

app/views/items/_form.html.erb
<%= form_with(model: item) do |form| %>
  <% if item.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
        <% item.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :filename, "File Name", style: "display: block", class: "form-label" %>
    <%= form.text_field :filename, class: "form-control" %>
  </div>

  <div>
    <%= form.label :filetype, "File Type", style: "display: block", class: "form-label" %>
    <%= form.text_field :filetype, class: "form-control" %>
  </div>

  <div>
    <%= form.label :fileformat, "File Format", style: "display: block", class: "form-label" %>
    <%= form.text_field :fileformat, class: "form-control" %>
  </div>

  <div>
    <%= form.label :filesize, "File Size", style: "display: block", class: "form-label" %>
    <%= form.number_field :filesize, class: "form-control" %>
  </div>

  <div>
    <%= form.label :dimensions, style: "display: block", class: "form-label" %>
    <%= form.text_field :dimensions, class: "form-control" %>
  </div>

  <div>
    <%= form.label :content_description, style: "display: block", class: "form-label" %>
    <%= form.text_area :content_description, class: "form-control" %>
  </div>

  <div>
    <%= form.label :content_keywords, style: "display: block", class: "form-label" %>
    <%= form.text_area :content_keywords, class: "form-control" %>
  </div>

  <div>
    <%= form.label :file_date_created, style: "display: block", class: "form-label" %>
    <%= form.datetime_field :file_date_created, class: "form-control" %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/items/_gallery.html.erb
<div class="row row-cols-1 row-cols-md-3 g-4">
    <% items.each do |item| %>
    <div class="col">
      <div class="card h-100">
        <div class="card-header">
          <h5 class="card-title"><%= item.filename %></h5>
        </div>
        <div class="card-img-top" width="100%" height="100%">
          <% if item.fileobj.image? %>
            <%= image_tag item.fileobj.representation(resize_to_limit: [200, 200]), class: "img-thumbnail" %>
          <% elsif item.fileobj.text? %>
            <%= image_tag("document-svgrepo-com.svg", height: "200") %>
          <% elsif item.fileobj.audio? %>
            <%= image_tag("multimedia-volume-control-svgrepo-com.svg", height: "200") %>
          <% elsif item.fileobj.video? %>
            <%= image_tag("gnome-mplayer-svgrepo-com.svg", height: "200") %>
          <% else %>
            <svg class="bd-placeholder-img card-img-top" width="100%" height="200" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: No preview available" preserveAspectRatio="xMidYMid slice" focusable="false">
              <title>No Preview Available</title>
              <rect width="100%" height="100%" fill="#868e96"></rect>
              <text x="30%" y="50%" fill="#dee2e6" dy=".3em">No Preview Available</text>
            </svg>
          <% end %>
        </div>
        <div class="card-body">
          
          <p class="card-text"><%= item.content_description %></p>
          
        </div>
        <div class="card-footer">
          <%= link_to "Show this item", item, class: "btn btn-primary" %>
        </div>
      </div>
      </div>
    <% end %>
  </div>

app/views/items/_item.html.erb
<div id="<%= dom_id item %>">
  <p>
    <strong>Filename:</strong>
    <%= item.filename %>
  </p>

  <p>
    <strong>Filetype:</strong>
    <%= item.filetype %>
  </p>

  <p>
    <strong>Fileformat:</strong>
    <%= item.fileformat %>
  </p>

  <p>
    <strong>Filesize:</strong>
    <%= item.filesize %>
  </p>

  <p>
    <strong>Dimensions:</strong>
    <%= item.dimensions %>
  </p>

  <p>
    <strong>Content description:</strong>
    <%= item.content_description %>
  </p>

  <p>
    <strong>Content keywords:</strong>
    <%= item.content_keywords %>
  </p>

  <p>
    <strong>File date created:</strong>
    <%= item.file_date_created %>
  </p>

</div>

app/views/items/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col">
        <%= link_to "Show this item", @item %> |
        <%= link_to "Back to items", items_path %>
        
    </div>
  </div>
  <div class="row">
    <div class="col">
      <h2>Edit Metadata</h2>
      <hr>
      <%= render "form", item: @item %>
    </div>
    <div class="col">
      <% if @item.fileobj.representable? %>
        <% if @item.fileobj.image? %>
          <%= image_tag @item.fileobj, class: "img-fluid" %>
        <% end %>
      <% end %>
      <%= @item.fileobj.filename %>
    </div>
  </div>
</div>

app/views/items/index.html.erb
<div id="items" class="container">
  <%= render "gallery", items: @items %>
</div>

app/views/items/new.html.erb
<div>
  <%= link_to "Back to Gallery", items_path %>
</div>
<br>

<div class="form-holder">
  <div class="form-title">
    <h1>Add a new item</h1>
  </div>
  <%= form_with(model: @item) do |form| %>
    <div>
      <%= form.label :fileobj, "Upload a file", style: "display: block", class: "form-label" %>
      <%= form.file_field :fileobj %>
    </div>
  
    <div>
      <%= form.submit %>
    </div>
  <% end %>

  
</div>

app/views/items/search.html.erb
<h1>Search Results</h1>
<% if (@results.length > 0) %>
  <p><%= @summary %>
  <%= render "gallery", items: @results %>
<% else %>
  <p>No items found</p>
<% end %>

app/views/items/show.html.erb
<div class="container">
  <div class="row">
    <div class="col">
        <%= link_to "Edit this item", edit_item_path(@item) %> |
        <%= link_to "Back to items", items_path %>

        <%= button_to "Delete Item", @item, method: :delete, class: "btn btn-danger" %>
    </div>
  </div>
  <div class="row">
    <div class="col">
      <h2>Metadata</h2>
      <hr>
      <%= render @item %>
    </div>
    <div class="col">
      <% if @item.fileobj.representable? %>
        <% if @item.fileobj.image? %>
          <%= image_tag @item.fileobj, class: "img-fluid" %>
        <% elsif @item.fileobj.video? %>
          <%= image_tag @item.fileobj.preview(resize_to_limit: [100, 100]) %>
        <% end %>
      <% end %>
      <% if @item.fileobj.previewable? %>
        <%= image_tag @item.fileobj.preview(resize_to_limit: [100, 100]) %>
      <% end %>
      <%= @item.fileobj.filename %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DAMit</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css" rel="stylesheet" />
  </head>

  <body>
    <header class="p-3 text-bg-dark">
      <div class="container">
        <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
          <a href="/" class="d-flex align-items-center mb-2 mb-lg-0 text-white text-decoration-none">
            <svg class="bi me-2" width="40" height="32" role="img" aria-label="Bootstrap"><use xlink:href="#bootstrap"></use></svg>
          </a>

          <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
            <li><a href="/" class="nav-link px-2 text-secondary">Home</a></li>
            <li><a href="/items" class="nav-link px-2 text-white">Gallery</a></li>
            <li><a href="/items/new" class="nav-link px-2 text-white">Add New</a></li>
            <li><a href="#" class="nav-link px-2 text-white">Advanced Search</a></li>
            <li><a href="#" class="nav-link px-2 text-white">About</a></li>
          </ul>

          <div class="col-12 col-lg-auto mb-3 mb-lg-0 me-lg-3" >
            <%= form_with url: "/search", method: :get do |form| %>
              <%= form.search_field :filename, class: "form-control form-control-dark text-bg-dark", placeholder: "Search..." %>
              <%= form.submit "Search", class: "btn btn-secondary" %>
            <% end %>
          </div>

          <div class="text-end">
            <% if user_signed_in? %> 
            <div> Welcome <%= current_user.email %> </div> 
              <%= button_to "Sign out", destroy_user_session_path, method: :delete, class: "btn btn-warning" %> 
            <% else %>
              <%= button_to "Sign in", new_user_session_path, class: "btn btn-warning" %> 
            <% end %>
            <!--<button type="button" class="btn btn-outline-light me-2">Login</button>
            <button type="button" class="btn btn-warning">Sign-up</button>-->
          </div>
        </div>
      </div>
    </header>
    <main>
      <div class="container">
        <p class="notice" style="color: green"><%= notice %></p> 
        <p class="alerts"><%= alert %></p> 
        <%= yield %>
      </div>
    </main>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
  </body>
</html>